title: 'Crabston Tutorials'
default_lang: de
author:
  name: 'Crabston GmbH'
  email: contact@crabston.dev
taxonomies:
  - category
  - tag
  - month
  - author
  - filter
metadata:
  description: 'Crabston Tutorials ist eine Seite der Crabston GmbH mit Anleitungen zu Grav CMS und diversen anderen Themen im Bereich Web und IT.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: '/tutorial'
